version: '3.5'
services:
  waardepapieren-service:
    volumes:
      - ./waardepapieren-service/system-test/certs:/certs:ro
      - ./waardepapieren-service/system-test/ephemeral-certs:/ephemeral-certs:ro
      - ./waardepapieren-service/configuration/:/app/configuration:ro
    build: waardepapieren-service/.
    ports:
      - 3232:3232
      - 3233:3233
      - 3235:3235
    environment:
      - WAARDEPAPIEREN_CONFIG=/app/configuration/waardepapieren-config-compose-travis.json
      - ULA_SERVER_ENDPOINT=https://0xvvmwxd6e.execute-api.eu-west-1.amazonaws.com/dev/sessions
      - ULA_BASIC_AUTH=aWN0dTp2NzdzaHZ6Z2VQeVpwUm9pQ3dhTzNETXljZlVVN0xNcGM4SG03bjlt
      # Ignore self-signed ephemeral cert issues
      - NODE_TLS_REJECT_UNAUTHORIZED=0

  waardepapieren-verblijfplaatshistorie-service:
    volumes:
      - ./waardepapieren-service/system-test/certs:/certs:ro
      - ./waardepapieren-service/system-test/ephemeral-certs:/ephemeral-certs:ro
      - ./waardepapieren-service/configuration/:/app/configuration:ro
    build: waardepapieren-service/.
    environment:
      - WAARDEPAPIEREN_CONFIG=/app/configuration/waardepapieren-verblijfplaatshistorie-config-compose-travis.json
      - ULA_SERVER_ENDPOINT=https://0xvvmwxd6e.execute-api.eu-west-1.amazonaws.com/dev/sessions
      - ULA_BASIC_AUTH=aWN0dTp2NzdzaHZ6Z2VQeVpwUm9pQ3dhTzNETXljZlVVN0xNcGM4SG03bjlt
      # Ignore self-signed ephemeral cert issues
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    restart: unless-stopped

  waardepapieren-uwv-service:
    volumes:
      - ./waardepapieren-service/system-test/certs:/certs:ro
      - ./waardepapieren-service/system-test/ephemeral-certs:/ephemeral-certs:ro
      - ./waardepapieren-service/configuration/:/app/configuration:ro
    build: waardepapieren-service/.
    environment:
      - WAARDEPAPIEREN_CONFIG=/app/configuration/waardepapieren-uwv-config-compose-travis.json
      - ULA_SERVER_ENDPOINT=https://0xvvmwxd6e.execute-api.eu-west-1.amazonaws.com/dev/sessions
      - ULA_BASIC_AUTH=aWN0dTp2NzdzaHZ6Z2VQeVpwUm9pQ3dhTzNETXljZlVVN0xNcGM4SG03bjlt
      # Ignore self-signed ephemeral cert issues
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    restart: unless-stopped

  mock-nlx:
    build: mock-nlx/
    ports:
      - 80:80

  mock-uwv:
    build: mock-uwv/
    ports:
      - 82:80

networks:
  default:
    name: waardepapieren
