version: '3.5'
services:
  waardepapieren-service:
    volumes:
      - ./waardepapieren-service/system-test/certs:/certs:ro
      - ./waardepapieren-service/system-test/ephemeral-certs:/ephemeral-certs:ro
      - ./waardepapieren-service/configuration/:/app/configuration:ro
    build: waardepapieren-service/.
    ports:
      - 3232:3232
      - 3233:3233
      - 3234:3234
      - 3235:3235
    environment:
      - WAARDEPAPIEREN_CONFIG=/app/configuration/waardepapieren-config-compose-travis.json
      - ULA_SERVER_ENDPOINT=$ULA_ENDPOINT
      - ULA_BASIC_AUTH=$ULA_BASIC_AUTH
      # Ignore self-signed ephemeral cert issues
      - NODE_TLS_REJECT_UNAUTHORIZED=0

  ictubank-frontend:
    build:
      context: ictubank-frontend/
      args:
        - CERTIFICATE_HOST=http://$CERT_HOST_IP:8880
        - IPV8_HOST=http://$CERT_HOST_IP
    depends_on:
      - waardepapieren-service
    ports:
      - 443:443
      - 8880:8880
    healthcheck:
      test: service nginx status
    volumes:
      - ./ictubank-frontend/nginx/certs:/etc/nginx/certs:ro

networks:
  default:
    name: waardepapieren
