version: '3'
services:
  waardepapieren-service:
    build: waardepapieren-service/.
    links:
      - mock-nlx
    ports:
      - 3232:3232
      - 3233:3233
    environment:
      - BASE64_EPHEMERAL_KEY=$BASE64_EPHEMERAL_KEY
      - BASE64_EPHEMERAL_CERT=$BASE64_EPHEMERAL_CERT
      - BASE64_NLX_KEY=$BASE64_NLX_KEY
      - BASE64_NLX_CERT=$BASE64_NLX_CERT
      - BASE64_WAARDEPAPIEREN_CONFIG=$BASE64_WAARDEPAPIEREN_CONFIG
      # Ignore self-signed ephemeral cert issues
      - NODE_TLS_REJECT_UNAUTHORIZED=0
  clerk-frontend:
    build:
      context: clerk-frontend/
      args:
        - CERTIFICATE_HOST=http://$CERT_HOST_IP:8880
    links:
      - waardepapieren-service
    ports:
      - 443:443
      - 8880:8880
    healthcheck:
      test: service nginx status
    environment:
      - BASE64_KEY=$BASE64_KEY
      - BASE64_CERT=$BASE64_CERT
  mock-nlx:
    build: mock-nlx/
    ports:
      - 80:80
